//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Orders')
export class OrdersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  orderId: number;

  @Column('integer', { nullable: true })
  customerId: number;

  @Column('real', { nullable: true })
  amount: number;

  @Column('text', { nullable: true })
  shippingAddress: string;

  @Column('text', { nullable: true })
  orderAddress: string;

  @Column('text', { nullable: true })
  orderEmail: string;

  @Column('date', { nullable: true })
  orderDate: Date;

  @Column('text', { nullable: true })
  orderStatus: string;

  @Column('integer', { nullable: true })
  orderFinalId: number;
}
