//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('tasks')
export class tasksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('date', { nullable: true })
  creationDate: Date;

  @Column('integer', { nullable: true })
  status: number;

  @Column('date', { nullable: true })
  updateStatusDate: Date;

  @Column('date', { nullable: true })
  deadline: Date;

  @Column('integer', { nullable: true })
  assignedUser: number;

  @Column('bool', { nullable: true })
  flagAlert: boolean;
}
