//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { usersEntity } from './db/users.entity';
import { tasksEntity } from './db/tasks.entity';
import { areasEntity } from './db/areas.entity';
import { statusesEntity } from './db/statuses.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      usersEntity,
      tasksEntity,
      areasEntity,
      statusesEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      users: [
        { name: 'name 1', email: 'email 1', role: 'role 1', id: 66 },
        { name: 'name 2', email: 'email 2', role: 'role 2', id: 38 },
        { name: 'name 3', email: 'email 3', role: 'role 3', id: 46 },
        { name: 'name 4', email: 'email 4', role: 'role 4', id: 96 },
        { name: 'name 5', email: 'email 5', role: 'role 5', id: 40 },
      ],
      tasks: [
        {
          title: 'title 1',
          description: 'description 1',
          creationDate: '2025-04-24T19:16:06.221Z',
          status: 1,
          updateStatusDate: '2024-02-02T04:33:36.061Z',
          deadline: '2024-01-31T00:43:54.404Z',
          assignedUser: 1,
          flagAlert: true,
          id: 53,
        },
        {
          title: 'title 2',
          description: 'description 2',
          creationDate: '2023-07-06T05:01:19.853Z',
          status: 2,
          updateStatusDate: '2024-06-14T19:00:44.672Z',
          deadline: '2024-05-17T18:37:17.071Z',
          assignedUser: 2,
          flagAlert: false,
          id: 15,
        },
        {
          title: 'title 3',
          description: 'description 3',
          creationDate: '2025-04-03T19:53:19.570Z',
          status: 3,
          updateStatusDate: '2025-03-23T06:22:19.383Z',
          deadline: '2024-09-26T02:37:39.380Z',
          assignedUser: 3,
          flagAlert: true,
          id: 100,
        },
        {
          title: 'title 4',
          description: 'description 4',
          creationDate: '2023-09-13T14:11:47.934Z',
          status: 4,
          updateStatusDate: '2024-07-14T08:01:27.458Z',
          deadline: '2023-09-29T07:33:45.764Z',
          assignedUser: 4,
          flagAlert: false,
          id: 72,
        },
        {
          title: 'title 5',
          description: 'description 5',
          creationDate: '2023-08-10T06:06:22.835Z',
          status: 5,
          updateStatusDate: '2024-10-31T23:25:20.121Z',
          deadline: '2025-02-21T02:50:01.552Z',
          assignedUser: 5,
          flagAlert: false,
          id: 74,
        },
      ],
      areas: [
        { title: 'title 1', description: 'description 1', id: 33 },
        { title: 'title 2', description: 'description 2', id: 59 },
        { title: 'title 3', description: 'description 3', id: 21 },
        { title: 'title 4', description: 'description 4', id: 44 },
        { title: 'title 5', description: 'description 5', id: 20 },
      ],
      statuses: [
        { title: 'title 1', description: 'description 1', id: 77 },
        { title: 'title 2', description: 'description 2', id: 89 },
        { title: 'title 3', description: 'description 3', id: 20 },
        { title: 'title 4', description: 'description 4', id: 16 },
        { title: 'title 5', description: 'description 5', id: 55 },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('usersEntity', data.users);
      await this.SeedResource('tasksEntity', data.tasks);
      await this.SeedResource('areasEntity', data.areas);
      await this.SeedResource('statusesEntity', data.statuses);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
