//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const tasksTitle = () => {
  const record = useRecordContext();
  return <span>tasks {record ? `"${record.title}"` : ''}</span>;
};

export const tasksList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="title" />
      <TextField source="description" />
      <DateField source="creationDate" />
      <ReferenceField source="status" reference="statuses" />
      <DateField source="updateStatusDate" />
      <DateField source="deadline" />
      <ReferenceField source="assignedUser" reference="users" />
      <BooleanField source="flagAlert" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const tasksEdit = () => (
  <Edit title={<tasksTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="title" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="description" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="creationDate" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="status" reference="statuses" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="updateStatusDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="deadline" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="assignedUser" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <BooleanInput source="flagAlert" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const tasksCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="title" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="description" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="creationDate" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="status" reference="statuses" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="updateStatusDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="deadline" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="assignedUser" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <BooleanInput source="flagAlert" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  <ReferenceInput
    source="status"
    label="status"
    reference="statuses"
    alwaysOn
  />,
  ,
  ,
  <ReferenceInput
    source="assignedUser"
    label="assignedUser"
    reference="users"
    alwaysOn
  />,
  ,
];
