//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    users: {
      name: 'Users',
      fields: { name: 'Name', email: 'Email', role: 'Role', id: 'id' },
    },
    tasks: {
      name: 'Tasks',
      fields: {
        title: 'Title',
        description: 'Description',
        creationDate: 'Creation Date',
        status: 'Status',
        updateStatusDate: 'Update Status Date',
        deadline: 'Deadline',
        assignedUser: 'Assigned User',
        flagAlert: 'Flag Alert',
        id: 'id',
      },
    },
    areas: {
      name: 'Areas',
      fields: { title: 'Title', description: 'Description', id: 'id' },
    },
    statuses: {
      name: 'Statuses',
      fields: { title: 'Title', description: 'Description', id: 'id' },
    },
  },
};
const frResources = {
  resources: {
    users: {
      name: 'Users (fr)',
      fields: {
        name: 'Name (fr)',
        email: 'Email (fr)',
        role: 'Role (fr)',
        id: 'id',
      },
    },
    tasks: {
      name: 'Tasks (fr)',
      fields: {
        title: 'Title (fr)',
        description: 'Description (fr)',
        creationDate: 'Creation Date (fr)',
        status: 'Status (fr)',
        updateStatusDate: 'Update Status Date (fr)',
        deadline: 'Deadline (fr)',
        assignedUser: 'Assigned User (fr)',
        flagAlert: 'Flag Alert (fr)',
        id: 'id',
      },
    },
    areas: {
      name: 'Areas (fr)',
      fields: {
        title: 'Title (fr)',
        description: 'Description (fr)',
        id: 'id',
      },
    },
    statuses: {
      name: 'Statuses (fr)',
      fields: {
        title: 'Title (fr)',
        description: 'Description (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
